### ISSUE TITLE
Improve Error Messaging

### ISSUE THREAD

**Issue by claireolmstead** [frequency-chain/testnet-faucet#22]
## Current Behavior
Returns "Error: Operation failed" or "Error: Assertion failed.", but I wish I knew why so I could resolve the problem.
![Image](https://github.com/user-attachments/assets/6af0839c-ee05-416e-aae4-70596c96d902)

## Expected Behavior
If possible, display a more in depth error message.

**Comment by claireolmstead** [comment]
@shannonwells Looks like we can close this out?

**Comment by shannonwells** [comment]
@claireolmstead I agree.
